### ISSUE TITLE
helm container creation fails crashloopbackoff

### ISSUE THREAD

**Issue by opvizordz** [dvonthenen/vsphere-metrics-prometheus#13]
When digging into the issue, the container fails to start prometheus because of the given prometheus.yml file.
 caller=main.go:717 err=\"error loading config from \\\"/etc/config/prometheus.yml\\\": couldn't load configuration (--config.file=\\\"/etc/config/prometheus.yml\\\"): parsing YAML file /etc/config/prometheus.yml: yaml: unmarshal errors:\\n  line 181: field vsphere_sd_configs not found in type config.plain\\n  line 208: field vsphere_sd_configs not found in type config.plain\\n  line 235: field vsphere_sd_configs not found in type config.plain

I tried to use different prometheus images as I noticed a debian issue, but the issue remains based on these three entries:
        vsphere_sd_configs:
          - role: esx
        vsphere_sd_configs:
          - role: datastore
        vsphere_sd_configs:
          - role: virtualmachine

**Comment by dvonthenen** [comment]
Hi @opvizordz 

This was a part of an effort that required a change to code within Prometheus itself to add discovery service for VMware based components. Unfortunately, the Prometheus maintainers would not accept the PR and therefore this project has currently been placed on the back burner until I get some time to refactor this project to remove that dependency.

**Comment by opvizordz** [comment]
Hi @dvonthenen thanks for the quick response. Could you point me to the PR? I would love to try it out.
Thanks

**Comment by dvonthenen** [comment]
@opvizordz https://github.com/prometheus/prometheus/pull/4323

**Comment by opvizordz** [comment]
Thanks a lot

**Comment by dvonthenen** [comment]
@opvizordz I assume you are running this in a Kubernetes environment correct? Are you also running the in-tree vsphere cloud provider functionality in Kubernetes?

**Comment by opvizordz** [comment]
@dvonthenen yes its a demo Kubernetes environment on top of vSphere. We're not yet running the vsphere cloud provider functionality - but looking into it these days. I can keep you posted.

**Comment by opvizordz** [comment]
@dvonthenen yes, we're running a demo Kubernetes environment on top of vSphere using the vSphere cloud provider.

**Comment by dvonthenen** [comment]
@opvizordz yea, I have floated around the idea of pushing all these metrics into the cloud provider and making it available there. Will see if I get enough time.
