### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by finkr** [dvonthenen/vsphere-metrics-prometheus#14]
Hello,

This project seemed promising, but...

It seems the vSphere Service Discovery integration in prometheus was not accepted [PR 4323](https://github.com/prometheus/prometheus/pull/4323). (Due to Prometheus's current policy _"Unfortunately, we are currently not accepting new integrations."_)

What's the roadmap for service discovery (standalone daemon to create a [file_sd](https://prometheus.io/blog/2018/07/05/implementing-custom-sd/)...?).

What's the roadmap for vsphere-metrics-prometheus ?

Thanks !

Franklin

**Comment by dvonthenen** [comment]
@finkr  Please see https://github.com/dvonthenen/vsphere-metrics-prometheus/issues/13

Until I get some time to work on this, it's just sitting on the back burner for now.
